### ISSUE TITLE
p-adic numbers with denominators that are multiples of p do not work

### ISSUE THREAD

**Issue by BMDragon** [GDeLaurentis/pyadic#1]
```PAdic(Q(1/5), 5, 20)*5``` should just produce 1, but instead gives ```1*5^3 + 2*5^5 + 2*5^6 + 4*5^7 + 2*5^8 + 2*5^9 + 2*5^11 + 1*5^12 + 4*5^13 + 4*5^17 + 4*5^18 + 3*5^20 + 3*5^21 + 3*5^22 + O(5^23)```

I believe this to be because a proper representation of 1/5 in 5-adic numbers is ...0000.1 . This would be 1*5^-1 in your representation, but that is not what is outputted. The issue also exists for other bases.

**Comment by GDeLaurentis** [comment]
Hi, thanks for pointing out this interesting behavior.

It looks like the issue is actually with how the rational number (`fractions.Fraction`) is instantiated. In your example, 1/5 is first cast to a floating-point number and then converted to a rational. More specifically, the issue is that `1/5` gets evaluated to not exactly `0.2`, but rather `0.20000000000000001`. You can see this using the package `mpmath`, doing `mpmath.mpf(1/5)`. On my machine, this results in `Q(1/5)` yielding `Fraction(3602879701896397, 18014398509481984)`, rather than the expected `Q(1,5)`. This number is close to 1/5 with the real metric, but not with the p-adic one. That ugly fraction is then converted to a p-adic number, I believe correctly. I think here you might have a different `Fraction` as my output for `PAdic(Q(1/5), 5, 20)*5` is different.

I would recommend doing `PAdic(Q(1, 5), 5, 20)*5` or `PAdic(Q('1/5'), 5, 20)*5`, both of which give the correct result `1*5^-1 + O(5^19)`. While this behavior is a bit annoying, I think the package is working as intented.

**Comment by BMDragon** [comment]
Ah, got it. Thank you!
