### ISSUE TITLE
when prime is 2

### ISSUE THREAD

**Issue by funfwo** [GDeLaurentis/pyadic#4]
![屏幕截图 2024-03-13 110837](https://github.com/GDeLaurentis/pyadic/assets/462304/8f7155ac-8d7f-417d-bb70-0bbe18b603ac)

May the circumstance of prime 2 has something weird.

Second, the significant digits. Could them not be figured out by the method itself instead of being indicated by users?

Thanks.

**Comment by GDeLaurentis** [comment]
Hello,

indeed prime=2 is a very extreme case, but what you tried should have worked. I just had not considered/implemented the rationalisation of p-adic numbers other than p-adic integers (i.e. whenever the p-adic number starts with a non-zero power of the prime). This is now fixed with this [commit](https://github.com/GDeLaurentis/pyadic/commit/1b8577145d682b34c49f58969f736eb3cf78207c).

Your example should now correctly return `Fraction(3, 8)`.

In general, note that the map $\mathbb{Q}_p \rightarrow \mathbb{Z}$ is not unique. You will get the intended result only for small numbers compared to prime ^ digits.

As for the number of significant digits, that is really up to the user. Perhaps, there could be a default value, making it an optional parameter, but I'm not sure what a reasonable default would be. Something where the number of digits decreases as the value of the prime increases might make sense, e.g. to fit the mantissa in 64-bit integers. But for now I'd rather leave this as a required parameter ([Explicit is better than implicit](https://peps.python.org/pep-0020/)).

Thank you for opening this issue!
